---
output:
  md_document:
    variant: markdown_github
---

```{r, setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'J:/___ctd-background/2301-c.c0-evaluacion-stock-modelos-estructurales/pub/')
knitr::opts_chunk$set(
  collapse = TRUE,
  tidy=TRUE,
  comment = "#>",
  fig.path = "R/README-2022/README-")
```

# Evaluación de Stocks usando Modelos Estructurados

Curso Teórico-Práctico de Evaluación de Stocks usando Modelos Estructurados. Este se llevará a cabo del 09 al 13 de enero del 2023, en el Auditorio Jorge Sánchez Romero IMARPE / Sede Central. 

# Programa



+ *Teoría y comportamiento de modelos estructurados por edad mediante simulación.*

$TAC_t  = TAC_(t-1) + b*\delta*CPUE$
$TAC_t  = TAC_(t-1) + b*Reclutamiento$

  + M1: Seguimientos de los números totales
  + M2: Estructura de edad
  + M3: Crecimiento corporal

+ Continuación de teoría y comportamiento de modelos estructurados por edad y
estimación de parámetros.

+ Introducción a Stock Synthesis (SS).

+ Configuración avanzada en SS y aplicación a sus propios datos.

+ Continuación de trabajo con sus propios datos, presentación de resultados
preliminares y discusión
